openapi: 3.0.3
info:
  title: Home Test Supplier API
  description: API for supplier domain operations - managing test results and order status updates
  version: 1.0.0

paths:
  /result:
    post:
      summary: Post Test Results
      description: Submit test results for a completed order
      tags:
        - Result Service
      parameters:
        - name: X-Correlation-ID
          in: header
          required: true
          description: Unique identifier for request tracking and idempotency
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/FHIRObservation'
      responses:
        '201':
          description: Results posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_uid:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  result_status:
                    type: string
                    example: "RECEIVED"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-11-04T15:45:00Z"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /test-order/status:
    put:
      summary: Update Order Status
      description: Update the status of an existing order using FHIR Task resource
      tags:
        - Order Management
      parameters:
        - name: X-Correlation-ID
          in: header
          required: true
          description: Unique identifier for request tracking and idempotency
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/FHIRTask'
      responses:
        '200':
          description: Status updated successfully
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIRTask'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    FHIRObservation:
      type: object
      description: FHIR Observation resource for test results
      required:
        - resourceType
        - status
        - code
        - subject
      properties:
        resourceType:
          type: string
          enum: [Observation]
          example: "Observation"
        id:
          type: string
          description: Logical id of this artifact
          example: "obs-550e8400-e29b-41d4-a716-446655440000"
        basedOn:
          type: array
          description: Reference to the ServiceRequest this observation fulfills
          items:
            type: object
            properties:
              reference:
                type: string
                example: "ServiceRequest/550e8400-e29b-41d4-a716-446655440000"
        status:
          type: string
          description: Status of the observation result
          enum: [registered, preliminary, final, amended, corrected, cancelled, entered-in-error, unknown]
          example: "final"
        code:
          type: object
          description: Type of observation (SNOMED CT or LOINC)
          properties:
            coding:
              type: array
              items:
                type: object
                properties:
                  system:
                    type: string
                    example: "http://snomed.info/sct"
                  code:
                    type: string
                    example: "31676001"
                  display:
                    type: string
                    example: "HIV antibody test - self-sampling"
        subject:
          type: object
          description: Patient reference for matching with service request - PII removed for results
          required:
            - reference
          properties:
            reference:
              type: string
              description: Reference to patient for matching purposes only
              example: "Patient/123e4567-e89b-12d3-a456-426614174000"
        effectiveDateTime:
          type: string
          format: date-time
          description: When the observation was made
          example: "2025-11-04T15:45:00Z"
        issued:
          type: string
          format: date-time
          description: Date/Time this version was made available
          example: "2025-11-04T16:00:00Z"
        performer:
          type: array
          description: Who is responsible for the observation
          items:
            type: object
            properties:
              reference:
                type: string
                example: "Organization/SUP001"
        valueQuantity:
          type: object
          description: Actual result (for numeric results)
          properties:
            value:
              type: number
              example: 0.5
            unit:
              type: string
              example: "index"
            system:
              type: string
              example: "http://unitsofmeasure.org"
            code:
              type: string
              example: "1"
        valueCodeableConcept:
          type: object
          description: Actual result (for coded results)
          properties:
            coding:
              type: array
              items:
                type: object
                properties:
                  system:
                    type: string
                    example: "http://snomed.info/sct"
                  code:
                    type: string
                    example: "260415000"
                  display:
                    type: string
                    example: "Not detected"

    FHIRTask:
      type: object
      description: FHIR Task resource for tracking order status
      required:
        - resourceType
        - status
        - basedOn
      properties:
        resourceType:
          type: string
          enum: [Task]
          example: "Task"
        id:
          type: string
          description: Logical id of this artifact
          example: "task-550e8400-e29b-41d4-a716-446655440000"
        identifier:
          type: array
          description: Task Instance Identifier
          items:
            type: object
            properties:
              system:
                type: string
                example: "https://fhir.hometest.nhs.uk/Id/order-uid"
              value:
                type: string
                example: "550e8400-e29b-41d4-a716-446655440000"
        basedOn:
          type: array
          description: Request fulfilled by this task
          items:
            type: object
            properties:
              reference:
                type: string
                example: "ServiceRequest/550e8400-e29b-41d4-a716-446655440000"
        status:
          type: string
          description: Current status of the task - Alpha-specific business statuses
          enum: [order-received, dispatched, received-at-lab, complete]
          example: "dispatched"
        statusReason:
          type: object
          description: Reason for current status
          properties:
            text:
              type: string
              example: "Sample collected and being processed"
        for:
          type: object
          description: Beneficiary of the Task
          properties:
            reference:
              type: string
              example: "Patient/123e4567-e89b-12d3-a456-426614174000"
        authoredOn:
          type: string
          format: date-time
          description: Task Creation Date
          example: "2025-11-04T10:30:00Z"
        lastModified:
          type: string
          format: date-time
          description: Task Last Modified Date
          example: "2025-11-04T10:35:00Z"
        requester:
          type: object
          description: Who is asking for task to be done
          properties:
            reference:
              type: string
              example: "Organization/ORG001"
        owner:
          type: object
          description: Responsible individual for the task
          properties:
            reference:
              type: string
              example: "Organization/SUP001"
        businessStatus:
          type: object
          description: E.g. "Pending", "Processing", etc.
          properties:
            text:
              type: string
              example: "Sample dispatched to laboratory"

  responses:
    BadRequest:
      description: Bad request - invalid parameters
      content:
        application/problem+json:
          schema:
            type: object
            required:
              - type
              - title
              - status
            properties:
              type:
                type: string
                format: uri
                description: Problem type URI
                example: "https://hometest.nhs.uk/problems/validation-error"
              title:
                type: string
                description: Short, human-readable summary
                example: "Validation Error"
              status:
                type: integer
                description: HTTP status code
                example: 400
              detail:
                type: string
                description: Human-readable explanation
                example: "The request contains invalid data that cannot be processed"
              instance:
                type: string
                format: uri
                description: URI identifying the specific problem occurrence
                example: "/result/errors/001"

    Unauthorized:
      description: Unauthorized - invalid or missing authentication
      content:
        application/problem+json:
          schema:
            type: object
            required:
              - type
              - title
              - status
            properties:
              type:
                type: string
                format: uri
                description: Problem type URI
                example: "https://hometest.nhs.uk/problems/authentication-required"
              title:
                type: string
                description: Short, human-readable summary
                example: "Authentication Required"
              status:
                type: integer
                description: HTTP status code
                example: 401
              detail:
                type: string
                description: Human-readable explanation
                example: "Valid authentication credentials are required to access this resource"
              instance:
                type: string
                format: uri
                description: URI identifying the specific problem occurrence
                example: "/result/errors/002"

    NotFound:
      description: Resource not found
      content:
        application/problem+json:
          schema:
            type: object
            required:
              - type
              - title
              - status
            properties:
              type:
                type: string
                format: uri
                description: Problem type URI
                example: "https://hometest.nhs.uk/problems/resource-not-found"
              title:
                type: string
                description: Short, human-readable summary
                example: "Resource Not Found"
              status:
                type: integer
                description: HTTP status code
                example: 404
              detail:
                type: string
                description: Human-readable explanation
                example: "The requested order could not be found"
              instance:
                type: string
                format: uri
                description: URI identifying the specific problem occurrence
                example: "/test-order/status/errors/001"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    NHS_Login:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.nhs.uk/oauth2/authorize
          tokenUrl: https://auth.nhs.uk/oauth2/token
          scopes:
            read: Read access to test information
            write: Write access to create orders
            admin: Administrative access

security:
  - BearerAuth: []
  - NHS_Login: []