openapi: 3.0.3
info:
  title: Home Test Supplier API
  description: API for supplier domain operations - managing test results and order status updates
  version: 1.0.0

paths:
  /result:
    post:
      summary: Post Test Results
      description: Submit test results for a completed order
      tags:
        - Result Service
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/FHIRObservation'
      responses:
        '201':
          description: Results posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_uid:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  result_status:
                    type: string
                    example: "RECEIVED"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-11-04T15:45:00Z"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /test-order/status:
    put:
      summary: Update Order Status
      description: Update the status of an existing order using FHIR Task resource
      tags:
        - Order Management
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/FHIRTask'
      responses:
        '200':
          description: Status updated successfully
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIRTask'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    FHIRObservation:
      type: object
      description: FHIR Observation resource for test results
      required:
        - resourceType
        - status
        - code
        - subject
      properties:
        resourceType:
          type: string
          enum: [Observation]
          example: "Observation"
        id:
          type: string
          description: Logical id of this artifact
          example: "obs-550e8400-e29b-41d4-a716-446655440000"
        basedOn:
          type: array
          description: Reference to the ServiceRequest this observation fulfills
          items:
            type: object
            properties:
              reference:
                type: string
                example: "ServiceRequest/550e8400-e29b-41d4-a716-446655440000"
        status:
          type: string
          description: Status of the observation result
          enum: [registered, preliminary, final, amended, corrected, cancelled, entered-in-error, unknown]
          example: "final"
        code:
          type: object
          description: Type of observation (SNOMED CT or LOINC)
          properties:
            coding:
              type: array
              items:
                type: object
                properties:
                  system:
                    type: string
                    example: "http://snomed.info/sct"
                  code:
                    type: string
                    example: "31676001"
                  display:
                    type: string
                    example: "HIV antibody test - self-sampling"
        subject:
          type: object
          description: Who and/or what the observation is about
          properties:
            reference:
              type: string
              example: "Patient/123e4567-e89b-12d3-a456-426614174000"
            firstName:
              type: string
              description: Patient's first name
              example: "John"
            lastName:
              type: string
              description: Patient's last name
              example: "Smith"
            dateOfBirth:
              type: string
              format: date
              description: Patient's date of birth
              example: "1985-03-15"
            address:
              type: object
              description: Patient's address
              properties:
                line1:
                  type: string
                  description: First line of address
                  example: "123 Main Street"
                line2:
                  type: string
                  description: Second line of address (optional)
                  example: "Apartment 2B"
                city:
                  type: string
                  description: City or town
                  example: "London"
                postcode:
                  type: string
                  description: Postal code
                  example: "SW1A 1AA"
                country:
                  type: string
                  description: Country
                  example: "United Kingdom"
        effectiveDateTime:
          type: string
          format: date-time
          description: Clinically relevant time/time-period for observation
          example: "2025-11-04T15:45:00Z"
        issued:
          type: string
          format: date-time
          description: Date/Time this version was made available
          example: "2025-11-04T16:00:00Z"
        performer:
          type: array
          description: Who is responsible for the observation
          items:
            type: object
            properties:
              reference:
                type: string
                example: "Organization/SUP001"
        valueQuantity:
          type: object
          description: Actual result value (for numeric results)
          properties:
            value:
              type: number
              example: 0.5
            unit:
              type: string
              example: "index"
            system:
              type: string
              example: "http://unitsofmeasure.org"
            code:
              type: string
              example: "1"
        valueCodeableConcept:
          type: object
          description: Actual result value (for coded results)
          properties:
            coding:
              type: array
              items:
                type: object
                properties:
                  system:
                    type: string
                    example: "http://snomed.info/sct"
                  code:
                    type: string
                    example: "260415000"
                  display:
                    type: string
                    example: "Not detected"
        valueString:
          type: string
          description: Actual result value (for text results)
          example: "Normal range"
        interpretation:
          type: array
          description: High, low, normal, etc.
          items:
            type: object
            properties:
              coding:
                type: array
                items:
                  type: object
                  properties:
                    system:
                      type: string
                      example: "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
                    code:
                      type: string
                      example: "N"
                    display:
                      type: string
                      example: "Normal"
        referenceRange:
          type: array
          description: Provides guide for interpretation
          items:
            type: object
            properties:
              low:
                type: object
                properties:
                  value:
                    type: number
                    example: 3.5
                  unit:
                    type: string
                    example: "mmol/L"
              high:
                type: object
                properties:
                  value:
                    type: number
                    example: 7.0
                  unit:
                    type: string
                    example: "mmol/L"
              text:
                type: string
                example: "Reference range for HIV antibody index"

    FHIRTask:
      type: object
      description: FHIR Task resource for tracking order status
      required:
        - resourceType
        - status
        - intent
        - basedOn
      properties:
        resourceType:
          type: string
          enum: [Task]
          example: "Task"
        id:
          type: string
          description: Logical id of this artifact
          example: "task-550e8400-e29b-41d4-a716-446655440000"
        identifier:
          type: array
          description: Task Instance Identifier
          items:
            type: object
            properties:
              system:
                type: string
                example: "https://fhir.hometest.nhs.uk/Id/order-uid"
              value:
                type: string
                example: "550e8400-e29b-41d4-a716-446655440000"
        basedOn:
          type: array
          description: Request fulfilled by this task
          items:
            type: object
            properties:
              reference:
                type: string
                example: "ServiceRequest/550e8400-e29b-41d4-a716-446655440000"
        status:
          type: string
          description: Current status of the task
          enum: [draft, requested, received, accepted, rejected, ready, cancelled, in-progress, on-hold, failed, completed, entered-in-error]
          example: "in-progress"
        statusReason:
          type: object
          description: Reason for current status
          properties:
            text:
              type: string
              example: "Sample collected and being processed"
        intent:
          type: string
          description: Intent of the task
          enum: [unknown, proposal, plan, order, original-order, reflex-order, filler-order, instance-order, option]
          example: "order"
        priority:
          type: string
          description: Priority of the task
          enum: [routine, urgent, asap, stat]
          example: "routine"
        code:
          type: object
          description: Task Type
          properties:
            coding:
              type: array
              items:
                type: object
                properties:
                  system:
                    type: string
                    example: "http://hl7.org/fhir/CodeSystem/task-code"
                  code:
                    type: string
                    example: "fulfill"
                  display:
                    type: string
                    example: "Fulfill the focal request"
        for:
          type: object
          description: Beneficiary of the Task
          properties:
            reference:
              type: string
              example: "Patient/123e4567-e89b-12d3-a456-426614174000"
        authoredOn:
          type: string
          format: date-time
          description: Task Creation Date
          example: "2025-11-04T10:30:00Z"
        lastModified:
          type: string
          format: date-time
          description: Task Last Modified Date
          example: "2025-11-04T10:35:00Z"
        requester:
          type: object
          description: Who is asking for task to be done
          properties:
            reference:
              type: string
              example: "Organization/ORG001"
        owner:
          type: object
          description: Responsible individual for the task
          properties:
            reference:
              type: string
              example: "Organization/SUP001"
        businessStatus:
          type: object
          description: E.g. "Pending", "Processing", etc.
          properties:
            text:
              type: string
              example: "Sample dispatched to laboratory"

  responses:
    BadRequest:
      description: Bad request - invalid parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid postcode format"
              error_code:
                type: string
                example: "INVALID_POSTCODE"

    Unauthorized:
      description: Unauthorized - invalid or missing authentication
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid authentication credentials"
              error_code:
                type: string
                example: "UNAUTHORIZED"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Order not found"
              error_code:
                type: string
                example: "ORDER_NOT_FOUND"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    NHS_Login:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.nhs.uk/oauth2/authorize
          tokenUrl: https://auth.nhs.uk/oauth2/token
          scopes:
            read: Read access to test information
            write: Write access to create orders
            admin: Administrative access

security:
  - BearerAuth: []
  - NHS_Login: []